function u(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}
function ca(a,b,e){b=b*Math.PI/180;var d=Math.cos(b),c=Math.sin(b),f,g;f=e[0];g=e[1];b=e[2];if(1==f&&0==g&&0==b)return[a[0],a[1],a[2],a[3],d*a[4]+a[8]*c,d*a[5]+a[9]*c,d*a[6]+a[10]*c,d*a[7]+a[11]*c,d*a[8]-c*a[4],d*a[9]-c*a[5],d*a[10]-c*a[6],d*a[11]-c*a[7],a[12],a[13],a[14],a[15]];if(0==f&&1==g&&0==b)return[d*a[0]-c*a[8],d*a[1]-c*a[9],d*a[2]-c*a[10],d*a[3]-c*a[11],a[4],a[5],a[6],a[7],d*a[8]+a[0]*c,d*a[9]+a[1]*c,d*a[10]+a[2]*c,d*a[11]+a[3]*c,a[12],a[13],a[14],a[15]];if(0==f&&0==g&&1==b)return[d*a[0]+
a[4]*c,d*a[1]+a[5]*c,d*a[2]+a[6]*c,d*a[3]+a[7]*c,d*a[4]-c*a[0],d*a[5]-c*a[1],d*a[6]-c*a[2],d*a[7]-c*a[3],a[8],a[9],a[10],a[11],a[12],a[13],a[14],a[15]];if(0==f&&0==g&&0==b)return a.slice(0,16);e=1/Math.sqrt(f*f+g*g+b*b);f*=e;g*=e;b*=e;var h=g*g,n=1-d,k=f*g,l=g*b;e=f*c;g*=c;var r=b*c,c=n*l,m=n*k,t=n*f*b;f=d+n*f*f;k=m+r;l=t-g;h=d+n*h;r=m-r;m=c+e;d+=n*b*b;b=t+g;e=c-e;return[a[0]*f+a[4]*k+a[8]*l,a[1]*f+a[5]*k+a[9]*l,a[10]*l+a[2]*f+a[6]*k,a[11]*l+a[3]*f+a[7]*k,a[0]*r+a[4]*h+a[8]*m,a[1]*r+a[5]*h+a[9]*m,
a[10]*m+a[2]*r+a[6]*h,a[11]*m+a[3]*r+a[7]*h,a[0]*b+a[4]*e+a[8]*d,a[1]*b+a[5]*e+a[9]*d,a[10]*d+a[2]*b+a[6]*e,a[11]*d+a[3]*b+a[7]*e,a[12],a[13],a[14],a[15]]}function da(a){function b(){a();A(b)}a();A(b)}function E(a){return a&&"compileShader"in a}function A(a){var b=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame;b?b(a):window.setTimeout(a,17)}
function ea(){var a,b;function e(a,b,d,e){return a[b]==a[d]&&a[b+1]==a[d+1]&&a[b+2]==a[d+2]||a[e]==a[d]&&a[e+1]==a[d+1]&&a[e+2]==a[d+2]||a[b]==a[e]&&a[b+1]==a[e+1]&&a[b+2]==a[e+2]}a=1;var d,c,f;"undefined"==typeof a&&(a=1);"undefined"==typeof b&&(b=6);if(0>=b)throw Error("div must be 1 or more");b=1<<b;for(var g=[],h=[],n=[],k=[],l=[],r,m=b-1;0<=m;m--){var t=-90+180*m/b;if(0==m)g[0]=0,g[1]=-1;else{var w=Math.PI/180*t,t=Math.cos(w),w=Math.sin(w);g[2*m]=t;g[2*m+1]=w}m==b-1?(h[2*m]=0,h[2*m+1]=1):(h[2*
m]=g[2*m+2],h[2*m+1]=g[2*m+3])}n[0]=1;n[1]=0;for(m=1;m<2*b;m++){var t=Math.PI/180*(360*m/b),p=Math.cos(t),D=Math.sin(t);n.push(p,D)}for(m=0;m<b;m++){r=!0;for(var t=g[2*m],w=g[2*m+1],y=h[2*m],B=h[2*m+1],z=1*m/b,F=1*(m+1)/b,C=0;C<2*b;C++){var p=n[2*C],D=n[2*C+1],q=x,x=1*(b-C)/b,x=x-.25;0>x&&(x+=1);d=-p*t;c=w;f=D*t;l.push(a*d,a*c,a*f,-d,-c,-f,0,0);d=-p*y;c=B;f=D*y;l.push(a*d,a*c,a*f,-d,-c,-f,0,0);r||(p=l.length/8-4,d=8*p,c=d+6,l[c]=q,l[c+1]=z,l[c+8]=q,l[c+9]=F,l[c+16]=x,l[c+17]=F,l[c+24]=x,l[c+25]=z,
0==m||m==b-1?(e(l,d,d+8,d+16)||k.push(p,p+1,p+2),e(l,d+8,d+16,d+24)||k.push(p+2,p+1,p+3)):k.push(p,p+1,p+2,p+2,p+1,p+3));r=!1}}return new G(l,k,G.p)}
function H(a,b,e){null==b&&(b="attribute vec3 position;\nattribute vec3 normal;\nattribute vec2 textureUV;\nattribute vec3 colorAttr;\nuniform mat4 world;\nuniform mat4 view;\nuniform mat4 projection;\nvarying vec2 textureUVVar;\nvarying vec3 colorAttrVar;\nuniform mat4 viewInverse; /* internal */\nuniform mat3 worldInverseTrans3; /* internal */\nuniform float alpha;\nuniform vec4 lightPosition;\nuniform vec3 sa;\nuniform vec3 ma;\nuniform vec3 sd;\nuniform vec3 md;\nuniform vec3 ss;\nuniform vec3 ms;\nuniform float mshin;\nvarying vec3 ambientAndSpecularVar;\nvarying vec3 diffuseVar;\nvoid main(){\nvec4 positionVec4=vec4(position,1.0);\n",b+=
"vec4 worldPosition=world*positionVec4;\nvec3 sdir;\nfloat attenuation;\nif(lightPosition.w == 0.0){\n sdir=normalize(vec3(lightPosition));\n attenuation=1.0;\n} else {\n vec3 vertexToLight=vec3(lightPosition-worldPosition);\n float dist=length(vertexToLight);\n sdir=normalize(vertexToLight);\n attenuation=1.0/(1.0*dist);\n}\nvec3 transformedNormal=normalize(worldInverseTrans3*normal);\nfloat diffInt=dot(transformedNormal,sdir);vec3 viewPosition=normalize(vec3(viewInverse*vec4(0,0,0,1)-worldPosition));\nvec3 ambientAndSpecular=sa*ma;\nif(diffInt>=0.0){\n   // specular reflection\n   ambientAndSpecular+=(ss*ms*pow(max(dot(reflect(-sdir,transformedNormal),      viewPosition),0.0),mshin));\n}\ndiffuseVar=sd*md*max(0.0,dot(transformedNormal,sdir))*attenuation;\nambientAndSpecularVar=ambientAndSpecular;\n",
b+="colorAttrVar=colorAttr;\n",b+="textureUVVar=textureUV;\n",b+="gl_Position=projection*view*world*positionVec4;\n}");null==e&&(e="precision highp float;\nuniform sampler2D sampler;\nuniform float useTexture;\nuniform float useColorAttr;\nvarying vec2 textureUVVar;\nvarying vec3 colorAttrVar;\nvarying vec3 ambientAndSpecularVar;\nvarying vec3 diffuseVar;\n",e+="void main(){\n",e+=" vec4 baseColor;\n",e+=" baseColor=vec4(1.0,1.0,1.0,1.0)*(1.0-useTexture);\n",e+=" baseColor+=texture2D(sampler,textureUVVar)*useTexture;\n baseColor=baseColor*(1.0-useColorAttr) +\n  vec4(colorAttrVar,1.0)*useColorAttr;\n",
e+=" vec3 phong=ambientAndSpecularVar+diffuseVar*baseColor.rgb;\n gl_FragColor=vec4(phong,baseColor.a);\n",e+="}");this.c=fa(a,b,e);this.attributes={};this.a=a;this.s={};this.K={};if(null!=this.c){this.attributes=[];var d=null;b={};e=a.getProgramParameter(this.c,a.ACTIVE_ATTRIBUTES);for(var c=0;c<e;++c)if(d=a.getActiveAttrib(this.c,c),null!==d){var d=d.name,f=a.getAttribLocation(this.c,d);0<=f&&(this.attributes.push(f),b[d]=f)}e=a.getProgramParameter(this.c,a.ACTIVE_UNIFORMS);for(c=0;c<e;++c)f=a.getActiveUniform(this.c,
c),null!==f&&(d=f.name,b[d]=a.getUniformLocation(this.c,d),this.K[d]=f.type);this.s=b}}H.prototype.get=function(a){return this.s.hasOwnProperty(a)?this.s[a]:null};
function I(a,b){for(var e in b)if(b.hasOwnProperty(e)){v=b[e];var d=a.get(e);null!==d&&(3==v.length?a.a.uniform3f(d,v[0],v[1],v[2]):4==v.length?a.a.uniform4f(d,v[0],v[1],v[2],v[3]):16==v.length?a.a.uniformMatrix4fv(d,!1,v):9==v.length?a.a.uniformMatrix3fv(d,!1,v):a.K[e]==a.a.FLOAT?a.a.uniform1f(d,"number"==typeof v?v:v[0]):a.a.uniform1i(d,"number"==typeof v?v:v[0]))}}
function fa(a,b,e){function d(a,b,d){var e=a.createShader(b);a.shaderSource(e,d);a.compileShader(e);return a.getShaderParameter(e,a.COMPILE_STATUS)?e:(console.log((b==a.VERTEX_SHADER?"vertex: ":"fragment: ")+a.getShaderInfoLog(e)),null)}b=b&&0!=b.length?d(a,a.VERTEX_SHADER,b):null;e=e&&0!=e.length?d(a,a.FRAGMENT_SHADER,e):null;var c=null;null!==b&&null!==e&&(c=a.createProgram(),a.attachShader(c,b),a.attachShader(c,e),a.linkProgram(c),a.getProgramParameter(c,a.LINK_STATUS)?a.useProgram(c):(console.log("link: "+
a.getProgramInfoLog(c)),a.deleteProgram(c),c=null));null!==b&&a.deleteShader(b);null!==e&&a.deleteShader(e);return c}H.prototype.l=function(a){if(!a)return this;I(this,{sa:[a.g[0],a.g[1],a.g[2]],lightPosition:a.position,sd:a.i,ss:a.m});return this};function J(){this.g=[0,0,0,1];this.position=[0,0,1,0];this.i=[1,1,1];this.m=[1,1,1]}function ga(){var a=[0,0,1],b=new J;b.g=[.25,.25,.25];b.position=a?[a[0],a[1],a[2],0]:[0,0,1,0];b.i=[1,1,1];b.m=[1,1,1];return b}
function O(a,b,e,d){this.kind=Materials.M;this.$=null==d?1:Math.min(Math.max(0,d),128);this.g=a||[.2,.2,.2];this.i=b||[.8,.8,.8];this.m=e||[0,0,0]}O.prototype.bind=function(a){I(a,{useTexture:0,mshin:this.$,ma:this.g,md:this.i,ms:this.m})};function G(a,b,e){this.F=a;this.f=b;this.format=e}G.N=2;G.O=3;G.p=6;G.P=5;G.G=7;
G.prototype.bind=function(a){var b=a.createBuffer(),e=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,b);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,e);a.bufferData(a.ARRAY_BUFFER,new Float32Array(this.F),a.STATIC_DRAW);var d=a.UNSIGNED_SHORT;65536<=this.F.length||65536<=this.f.length?(d=a.UNSIGNED_INT,a.bufferData(a.ELEMENT_ARRAY_BUFFER,new Uint32Array(this.f),a.STATIC_DRAW)):256>=this.F.length&&256>=this.f.length?(d=a.UNSIGNED_BYTE,a.bufferData(a.ELEMENT_ARRAY_BUFFER,new Uint8Array(this.f),a.STATIC_DRAW)):
a.bufferData(a.ELEMENT_ARRAY_BUFFER,new Uint16Array(this.f),a.STATIC_DRAW);return{ba:b,f:e,W:this.f.length,type:d,format:this.format}};
G.ca=function(a,b,e){for(var d=0;d<a.length;d+=e)a[d+3]=0,a[d+4]=0,a[d+5]=0;for(d=0;d<a.length;d+=3){var c=b[d]*e,f=b[d+1]*e,g=b[d+2]*e,h=[a[f]-a[g],a[f+1]-a[g+1],a[f+2]-a[g+2]],n=[a[c]-a[g],a[c+1]-a[g+1],a[c+2]-a[g+2]],k=h[1]*n[2]-h[2]*n[1],l=h[2]*n[0]-h[0]*n[2],h=h[0]*n[1]-h[1]*n[0];len=Math.sqrt(k*k+l*l+h*h);0!=len&&(len=1/len,k*=len,l*=len,h*=len,a[c+3]+=k,a[c+4]+=l,a[c+5]+=h,a[f+3]+=k,a[f+4]+=l,a[f+5]+=h,a[g+3]+=k,a[g+4]+=l,a[g+5]+=h)}for(d=0;d<a.length;d+=e)if(k=a[d+3],l=a[d+4],h=a[d+5],len=
Math.sqrt(k*k+l*l+h*h))len=1/len,a[d+3]=k*len,a[d+4]=l*len,a[d+5]=h*len};(function(){function a(a){this.a=a}a.TEXTURE=1;a.M=2;a.prototype.v=function(a,e,d){return"number"==typeof a&&"number"==typeof e&&"number"==typeof d?new O([a,e,d],[a,e,d]):new O(a,a)};window.Materials=a})(window);
function P(a){this.a=a;this.a.viewport(0,0,1*this.a.canvas.width,1*this.a.canvas.height);this.c=new H(a);this.h=[];this.clearColor=[0,0,0,1];this.Y=new Materials(a);this.a.enable(a.BLEND);this.Q=u();this.I=u();this.e=!0;this.H=this.q=null;this.B=new J;this.a.blendFunc(a.SRC_ALPHA,a.ONE_MINUS_SRC_ALPHA);this.a.enable(this.a.DEPTH_TEST);this.a.depthFunc(this.a.LEQUAL);Q(this);this.a.clearDepth(999999);this.a.clear(this.a.COLOR_BUFFER_BIT|this.a.DEPTH_BUFFER_BIT)}
P.prototype.useProgram=function(a){if(!a)throw Error("invalid program");a.a.useProgram(a.c);this.c=a;I(this.c,{sampler:0});this.c.l(this.B);this.e=!0;return this};function Q(a){a.a.clearColor(a.clearColor[0],a.clearColor[1],a.clearColor[2],a.clearColor[3]);return a}P.prototype.v=function(a,b,e,d){return this.Y.v(a,b,e,d)};
P.prototype.r=function(){if(this.e){var a;a=this.I;var b=a[0]*a[10],e=a[0]*a[11],d=a[0]*a[5],c=a[0]*a[6],f=a[0]*a[7],g=a[0]*a[9],h=a[10]*a[12],n=a[10]*a[13],k=a[10]*a[15],l=a[11]*a[12],r=a[11]*a[13],m=a[11]*a[14],t=a[1]*a[4],w=a[1]*a[6],p=a[1]*a[7],D=a[1]*a[8],y=a[2]*a[4],B=a[2]*a[5],z=a[2]*a[7],F=a[2]*a[8],C=a[2]*a[9],q=a[3]*a[4],x=a[3]*a[5],R=a[3]*a[6],S=a[3]*a[8],T=a[3]*a[9],U=a[4]*a[9],X=a[5]*a[8],Y=a[6]*a[8],Z=a[6]*a[9],aa=a[7]*a[8],ba=a[7]*a[9],K=t-d,L=w-B,M=p-x,N=y-c,d=d-t,w=B-w,B=z-R,t=q-
f,p=x-p,z=R-z,c=c-y,y=f-q,f=a[9]*a[12]*z+h*M+l*w+a[8]*a[13]*B+n*t+r*c+a[8]*a[14]*p+a[9]*a[14]*y+m*K+a[8]*a[15]*L+a[9]*a[15]*N+k*d;if(0==f)a=u();else{f=1/f;q=[];q[0]=a[6]*r-a[7]*n+ba*a[14]-a[5]*m-Z*a[15]+a[5]*k;q[1]=a[3]*n-a[2]*r-T*a[14]+a[1]*m+C*a[15]-a[1]*k;q[2]=a[13]*B+a[14]*p+a[15]*L;q[3]=a[9]*z+a[10]*M+a[11]*w;q[4]=a[7]*h-a[6]*l-aa*a[14]+a[4]*m+Y*a[15]-a[4]*k;q[5]=a[2]*l-a[3]*h+a[14]*(S-e)+a[15]*(b-F);q[6]=a[12]*z+a[14]*y+a[15]*N;q[7]=a[8]*B+a[10]*t+a[11]*c;q[8]=a[5]*l-ba*a[12]+aa*a[13]-a[4]*
r+a[15]*(U-X);q[9]=T*a[12]-a[1]*l+a[13]*(e-S)+a[15]*(D-g);q[10]=a[12]*M+a[13]*t+a[15]*d;q[11]=a[8]*p+a[9]*y+a[11]*K;q[12]=Z*a[12]-a[5]*h-Y*a[13]+a[4]*n+a[14]*(X-U);q[13]=a[1]*h-C*a[12]+a[13]*(F-b)+a[14]*(g-D);q[14]=a[12]*w+a[13]*c+a[14]*K;q[15]=a[8]*L+a[9]*N+a[10]*d;for(a=0;16>a;a++)q[a]*=f;a=q}this.H=a;I(this.c,{view:this.I,projection:this.Q,viewInverse:this.H});this.e=!1}};P.prototype.l=function(a){this.B=a;this.c.l(this.B);return this};
P.prototype.D=function(){this.r();this.a.clear(this.a.COLOR_BUFFER_BIT);for(var a=0;a<this.h.length;a++)this.h[a].D(this.c);this.a.flush()};function V(a,b){if(null==b)throw Error("vertfaces is null");this.o=b.constructor==G?b.bind(a):b;this.a=a;this.C=new O;this.scale=[1,1,1];this.t=0;this.position=[0,0,0];this.L=[0,0,0];this.U=!1;this.e=!0;this.q=[1,0,0,0,1,0,0,0,1];this.d=u()}
V.prototype.r=function(){this.e=!1;var a=this.scale;this.d=[a[0],0,0,0,0,a[1],0,0,0,0,a[2],0,0,0,0,1];0!=this.t&&(this.d=ca(this.d,this.t,this.L));this.d[12]+=this.position[0];this.d[13]+=this.position[1];this.d[14]+=this.position[2];var a=this.d,a=[a[0],a[1],a[2],a[4],a[5],a[6],a[8],a[9],a[10]],b=a[0]*a[4]*a[8]+a[3]*a[7]*a[2]+a[6]*a[1]*a[5]-a[6]*a[4]*a[2]-a[3]*a[1]*a[8]-a[0]*a[7]*a[5];0==b?a=[1,0,0,0,1,0,0,0,1]:(b=1/b,a=[(-a[5]*a[7]+a[4]*a[8])*b,(a[5]*a[6]-a[3]*a[8])*b,(-a[4]*a[6]+a[3]*a[7])*b,(a[2]*
a[7]-a[1]*a[8])*b,(-a[2]*a[6]+a[0]*a[8])*b,(a[1]*a[6]-a[0]*a[7])*b,(-a[2]*a[4]+a[1]*a[5])*b,(a[2]*a[3]-a[0]*a[5])*b,(-a[1]*a[3]+a[0]*a[4])*b]);this.q=a};
V.prototype.D=function(a){this.C&&this.C.bind(a);var b=this.a,e=this.o,d=a.get("position"),c=a.get("normal"),f=a.get("textureUV"),g=a.get("colorAttr");b.bindBuffer(b.ARRAY_BUFFER,e.ba);b.bindBuffer(b.ELEMENT_ARRAY_BUFFER,e.f);e=e.format;e==G.P?(W(b,d,3,b.FLOAT,24,0),W(b,c,3,b.FLOAT,24,12)):e==G.p?(W(b,d,3,b.FLOAT,32,0),W(b,c,3,b.FLOAT,32,12),W(b,f,2,b.FLOAT,32,24)):e==G.G?(W(b,d,3,b.FLOAT,24,0),W(b,g,3,b.FLOAT,24,12)):e==G.N?W(b,d,2,b.FLOAT,8,0):e==G.O&&W(b,d,3,b.FLOAT,12,0);b={};null!==a.get("world")&&
(this.e&&this.r(),b.world=this.d,b.worldInverseTrans3=this.q);b.useColorAttr=this.o.format==G.G?1:0;I(a,b);this.a.drawElements(this.U?this.a.LINES:this.a.TRIANGLES,this.o.W,this.o.type,0)};function W(a,b,e,d,c,f){null!==b&&(a.enableVertexAttribArray(b),a.vertexAttribPointer(b,e,d,!1,c,f))}
(function(a){function b(a){a=a||"#ff0000";this.height=this.width=1E3;var b=$("<canvas>").attr("width",this.width+"").attr("height",this.height+"").css({width:"100%",height:"100%",left:"0px",zIndex:-1,top:"0px",position:"fixed"});$("body").append(b);this.n=!0;this.count=0;if(b=b.get(0)){var c=null,f={antialias:!0};try{c=b.getContext("webgl",f)}catch(g){c=null}if(!c)try{c=b.getContext("experimental-webgl",f)}catch(h){c=null}if(!c)try{c=b.getContext("moz-webgl",f)}catch(n){c=null}if(!c)try{c=b.getContext("webkit-3d",
f)}catch(k){c=null}if(!c)try{c=b.getContext("2d",f)}catch(l){c=null}E(c)&&(c.getExtension("OES_element_index_uint"),c.getExtension("EXT_texture_filter_anisotropic"));b=c}else b=null;this.a=b;this.n=E(this.a);this.h=[];this.setColor(a)}b.aa=function(a){var d=a[0]-7.5+b.b(15);360<=d?d=360-d:0>d&&(d=360+d);var c=a[1],c=15>=c?b.b(30):240<c?240+b.b(30):c-15+b.b(30),f=a=a[2],f=15>=f?b.b(30):240<f?240+b.b(30):f+b.b(30);0<a&&0<c&&255>c&&(25>=c&&(c=25),242<=c&&(c=242));return[d,c,f]};b.b=function(a){return Math.random()*
a|0};b.Z=function(a){var b=a[0],c=a[1];a=a[2];var f=b;c>f&&(f=c);a>f&&(f=a);var g=b;c<g&&(g=c);a<g&&(g=a);var h=f+g,n=h/2;if(f===g)return[0,0>n?0:255<n?255:n,0];var g=f-g,h=255*g/(127.5>=n?h:510-h),k=0,k=g/2,k=b===f?(60*(f-a)+k)/g-(60*(f-c)+k)/g:a===f?240+(60*(f-c)+k)/g-(60*(f-b)+k)/g:120+(60*(f-b)+k)/g-(60*(f-a)+k)/g;if(0>k||360<=k)k=(k%360+360)%360;return[k,0>n?0:255<n?255:n,0>h?0:255<h?255:h]};b.A=function(a){var b=1*a[0],c=1*a[1],f=1*a[2],c=0>c?0:255<c?255:c,f=0>f?0:255<f?255:f;if(0===f)return[c,
c,c];a=0;127.5>=c?a=c*(255+f)/255:(a=c*f/255,a=c+f-a);var g=2*c-a;if(0>b||360<=b)b=(b%360+360)%360;var h=b+120;360<=h&&(h-=360);c=60>h?g+(a-g)*h/60:180>h?a:240>h?g+(a-g)*(240-h)/60:g;h=b;f=60>h?g+(a-g)*h/60:180>h?a:240>h?g+(a-g)*(240-h)/60:g;h=b-120;0>h&&(h+=360);b=60>h?g+(a-g)*h/60:180>h?a:240>h?g+(a-g)*(240-h)/60:g;return[0>c?0:255<c?255:c,0>f?0:255<f?255:f,0>b?0:255<b?255:b]};b.u=function(a){a="0"+(a|0).toString(16);return a.substring(a.length-2,a.length)};b.w=function(a){a=b.A(a);return"#"+b.u(a[0])+
b.u(a[1])+b.u(a[2])};b.X=function(a){return null==a||"undefined"==typeof a?null:(a=/^\#([A-F0-9]{2})([A-F0-9]{2})([A-F0-9]{2})$/i.exec(a))?[parseInt(a[1],16),parseInt(a[2],16),parseInt(a[3],16)]:null};b.prototype.start=function(){da(this.R.bind(this))};b.prototype.setColor=function(a){a=this.constructor.X(a);if(!a)throw Error("invalid color parameter");this.color=a;this.j=this.constructor.Z(a);this.T()};b.prototype.T=function(){document.body.style.backgroundColor=this.constructor.w(this.j);if(this.n){var a=
this.constructor.A(this.j);this.S=new G([-1,-1,1,1,0,0,1,1,-1,1,1,1,0,0,1,0,-1,1,-1,1,0,0,0,0,-1,-1,-1,1,0,0,0,1,1,-1,-1,-1,0,0,1,1,1,1,-1,-1,0,0,1,0,1,1,1,-1,0,0,0,0,1,-1,1,-1,0,0,0,1,1,-1,-1,0,1,0,1,1,1,-1,1,0,1,0,1,0,-1,-1,1,0,1,0,0,0,-1,-1,-1,0,1,0,0,1,1,1,1,0,-1,0,1,1,1,1,-1,0,-1,0,1,0,-1,1,-1,0,-1,0,0,0,-1,1,1,0,-1,0,0,1,-1,-1,-1,0,0,1,1,1,-1,1,-1,0,0,1,1,0,1,1,-1,0,0,1,0,0,1,-1,-1,0,0,1,0,1,1,-1,1,0,0,-1,1,1,1,1,1,0,0,-1,1,0,-1,1,1,0,0,-1,0,0,-1,-1,1,0,0,-1,0,1],[0,1,2,0,2,3,4,5,6,4,6,7,8,
9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23],G.p);this.J=ea();var b=(new P(this.a)).l(ga());b.clearColor=[a[0]/255,a[1]/255,a[2]/255,1];this.k=Q(b)}else this.a.fillStyle=this.constructor.w(this.j),this.a.fillRect(0,0,this.width,this.height)};b.prototype.R=function(){this.count++;4<=this.count&&(this.count=0,this.V());this.n&&this.k.D()};b.prototype.V=function(){var a=this.constructor.aa(this.j);if(this.n){300<this.h.length&&this.k.h.shift();var b=this.constructor.b(2E3)/1E3-
1,c=this.constructor.b(2E3)/1E3-1,f=this.constructor.b(60)/60,g=0==this.constructor.b(2)?this.S:this.J,h=(16+this.constructor.b(100))/1E3,n=this.constructor.A(a);n[0]/=255;n[1]/=255;n[2]/=255;var a=this.constructor.b(160),k=[this.constructor.b(360)/360,this.constructor.b(360)/360,this.constructor.b(30)/30],l=k[0],r=k[1],m=k[2];len=Math.sqrt(l*l+r*r+m*m);0!=len&&(len=1/len,k[0]*=len,k[1]*=len,k[2]*=len);l=new V(this.a,g);l.scale=[h,h,h];l.e=!0;h=this.k.v(n);if(g!=this.J||h.kind==Materials.TEXTURE)l.t=
a%360,l.L=k,l.e=!0;l.position=[b,c,f];l.e=!0;l.C=h;this.k.h.push(l)}else b=[this.constructor.b(this.width+30)-30,this.constructor.b(this.height+30)-30,32+this.constructor.b(200),32+this.constructor.b(200)],this.a.fillStyle=this.constructor.w(a),this.a.fillRect(b[0],b[1],b[2],b[3])};b.colorBackground=function(a){$(document).ready(function(){(new b(a)).start()})};a.CanvasBackground=b})(this);
